市区町村地図にポップアップ（tooltip）を実装
codeforosaka/covid19 pull request #636
Opened 2020-08-28 07:55 UTC by yukiyaxxxx

## 📝 関連issue / Related Issues

#635
#281 

## ⛏ 変更内容 / Details of Changes

- 市町村地図にマウスオーバー時のポップアップ（市名＋人数）を追加しました

## 📸 スクリーンショット / Screenshots
![スクリーンショット 2020-08-28 16 54 45](https://user-images.githubusercontent.com/59367678/91536137-38a13a80-e94f-11ea-9e1e-5ecf764d5483.png)

2020-08-28 11:13 UTC, mfmfuyu requested changes
レビューを行いましたので、ご確認のよろしくお願いします！
他の部分に関しては問題ないと思います！

2020-08-28 11:13 UTC, mfmfuyu commented on components/GraphicalMapCard.vue
> +              popData[d.properties.index].name +
```suggestion
              vm.$t(popData[d.properties.index].name) +
```
ツールチップの内容を多言語に対応する為に、上記のように変更が必要です。

また、上記の変更を動作させる為に`mounted()`や`drawOsaka()`の部分も下記の様に変更を行う必要があります。
```js
// ...
mounted() {
  loadYouseiData()
  drawOsaka(this, this.$refs.map.clientWidth)
// ...
```
```js
// ...
function drawOsaka(vm, elementWidth) {
// ...
```

2020-08-28 11:13 UTC, mfmfuyu commented on components/GraphicalMapCard.vue
> +              ' 人'
```suggestion
              vm.$t('人')
```
こちらも上記の230行目と同じ様に変更が必要となります。

2020-08-28 11:13 UTC, mfmfuyu commented on components/GraphicalMapCard.vue
> +    // // 左側にデータ表示
後ほど削除予定でしたら申し訳ないのですが、ここの部分はコメントアウトではなく完全に削除しても問題ありません。

2020-08-28 12:21 UTC, yukiyaxxxx commented
レビューありがとうございます！
翻訳関係見落としていてすみません
いただいた内容を反映し再プッシュいたしました

2020-08-28 15:46 UTC, mfmfuyu commented
確認しました、対応ありがとうございます！
これで問題ないと思うので、他のレビュアーの方のレビュー後にマージされると思います 👍

2020-08-29 15:34 UTC, Blue-Tone approved these changes

2020-08-29 15:34 UTC, merged